## PFG Bank: Credit Card Design

* Team-lead GitHub userid: rsm-xyz123
* Group name:
* Team member names:
    -
    -
    -
    -

## Setup

Please complete this python notebook with your group by answering the questions in `pfg-bank-msba.pdf`.

Create a Notebook with all your results and comments and push the Notebook to GitHub when your team is done. Make sure to connect the GitHub repo to GradeScope before the due date. All results MUST be reproducible (i.e., the TA and I must be able to recreate your output from the Jupyter Notebook without changes or errors). This means that you should NOT use any python-packages that are not part of the RSM-MSBA docker container.

> Note: Please do not install any packages as part of your Jupyter Notebook submission

This is a group assignment and you will be using Git and GitHub. If two people edit the same file at the same time you could get what is called a "merge conflict". This is not something serious but you should realize that Git will not decide for you who's changes to accept. The team-lead will have to determine the edits to use. To avoid merge conflicts, **always** "pull" changes to the repo before you start working on any files. Then, when you are done, save and commit your changes, and then push them to GitHub. Make "pull first" a habit!

If multiple people are going to work on the assignment at the same time I recommend you work in different notebooks. You can then `%run ...`  these "sub" notebooks from the main assignment file. You can seen an example of this in action below for the `model1.ipynb` notebook

Some group work-flow tips:

* Pull, edit, save, stage, commit, and push
* Schedule who does what and when
* Try to avoid working simultaneously on the same file
* If you are going to work simultaneously, do it in different notebooks, e.g.,
    - model1.ipynb, question1.ipynb, etc.
* Use the `%run ... ` command to bring different pieces of code together into the main jupyter notebook
* Put python functions in modules that you can import from your notebooks. See the example below for the `example` function defined in `utils/functions.py`

A graphical depiction of the group work-flow is shown below:

![](images/github-group-workflow.png)

![](images/github-group-workflow.png)

In [1]:
import pandas as pd
import pyrsm as rsm
rsm.__version__ # should be 0.9.23 or newer

'0.9.26'

## Question answers

In [2]:
data1 = pd.read_excel('data/exhibits.xls', sheet_name='exhibit1')
data2 = pd.read_excel('data/exhibits.xls', sheet_name='exhibit2')

In [3]:
data1

,date,apr,fixed_var,annual_fee,visamc,nr_mailed,non_resp,resp,bk_score,average_bk
0,April,16.8,Fixed,20,MC,167000,165467,1533,200,210
1,April,16.8,Fixed,0,MC,81000,78104,2896,200,210
2,April,19.8,Fixed,20,MC,143000,142410,590,200,210
3,April,19.8,Fixed,0,MC,100000,97948,2052,200,210
4,September,14.9,Fixed,20,Visa,177000,172671,4329,250,255
5,September,14.9,Variable,20,Visa,170000,166996,3004,250,255
6,September,16.8,Fixed,20,Visa,255000,252017,2983,250,255
7,September,19.8,Fixed,20,Visa,35000,34825,175,250,255
8,September,16.8,Fixed,0,Visa,65000,62484,2516,250,255
9,September,19.8,Fixed,0,Visa,95000,92885,2115,250,255
10,November,14.9,Fixed,20,Visa,82000,80239,1761,150,190
11,November,14.9,Fixed,0,Visa,50000,47549,2451,150,190
12,November,14.9,Variable,20,Visa,50000,49292,708,150,190
13,November,16.8,Fixed,20,Visa,50000,49627,373,150,190

## Melting Data

In [4]:
tools_mult_melt = pd.melt(
    data1,
    id_vars=["apr", "fixed_var", "annual_fee",'visamc', 'date','bk_score'],
    value_vars=["resp", "non_resp"],
    var_name="resp",
    value_name="freq",
)
tools_mult_melt['apr'] = tools_mult_melt['apr'].astype('category')
tools_mult_melt['annual_fee'] = tools_mult_melt['annual_fee'].astype('category')
tools_mult_melt['bk_socre'] = tools_mult_melt['bk_score'].astype('category')
tools_mult_melt

,apr,fixed_var,annual_fee,visamc,date,bk_score,resp,freq,bk_socre
0,16.8,Fixed,20,MC,April,200,resp,1533,200
1,16.8,Fixed,0,MC,April,200,resp,2896,200
2,19.8,Fixed,20,MC,April,200,resp,590,200
3,19.8,Fixed,0,MC,April,200,resp,2052,200
4,14.9,Fixed,20,Visa,September,250,resp,4329,250
5,14.9,Variable,20,Visa,September,250,resp,3004,250
6,16.8,Fixed,20,Visa,September,250,resp,2983,250
7,19.8,Fixed,20,Visa,September,250,resp,175,250
8,16.8,Fixed,0,Visa,September,250,resp,2516,250
9,19.8,Fixed,0,Visa,September,250,resp,2115,250
10,14.9,Fixed,20,Visa,November,150,resp,1761,150
11,14.9,Fixed,0,Visa,November,150,resp,2451,150
12,14.9,Variable,20,Visa,November,150,resp,708,150
13,16.8,Fixed,20,Visa,November,150,resp,373,150
14,16.8,Fixed,20,MC,April,200,non_resp,165467,200
15,16.8,Fixed,0,MC,April,200,non_resp,78104,200
16,19.8,Fixed,20,MC,April,200,non_resp,142410,200
17,19.8,Fixed,0,MC,April,200,non_resp,97948,200
18,14.9,Fixed,20,Visa,September,250,non_resp,172671,250
19,14.9,Variable,20,Visa,September,250,non_resp,166996,250
20,16.8,Fixed,20,Visa,September,250,non_resp,252017,250
21,19.8,Fixed,20,Visa,September,250,non_resp,34825,250
22,16.8,Fixed,0,Visa,September,250,non_resp,62484,250
23,19.8,Fixed,0,Visa,September,250,non_resp,92885,250
24,14.9,Fixed,20,Visa,November,150,non_resp,80239,150
25,14.9,Fixed,0,Visa,November,150,non_resp,47549,150
26,14.9,Variable,20,Visa,November,150,non_resp,49292,150
27,16.8,Fixed,20,Visa,November,150,non_resp,49627,150

## Model With vismac, date and interaction term

For here, we add interaction term of date and fixed_var because we think that the effect of fixed_var on the response variable would change over time. We also add vismac and date into our explanatory variables since we want to maximize the usage of our historical data.

In [5]:
lr1 = rsm.model.logistic(
    data = {'tools_mult': tools_mult_melt},
    rvar = "resp",lev = 'resp', evar = ['apr', 'fixed_var', 'annual_fee', 'visamc', 'date','bk_score'],
    ivar = ['date:fixed_var'],
    weights = 'freq'
)
lr1.summary()

Logistic regression (GLM)
Data                 : tools_mult
Response variable    : resp
Level                : resp
Explanatory variables: apr, fixed_var, annual_fee, visamc, date, bk_score
Weights used         : freq
Null hyp.: There is no effect of x on resp
Alt. hyp.: There is an effect of x on resp

                                        OR     OR%  coefficient  std.error  z.value p.value
Intercept                            0.689  -31.1%        -0.37      0.004  -89.682  < .001  ***
apr[16.8]                            0.464  -53.6%        -0.77      0.019  -39.607  < .001  ***
apr[19.8]                            0.252  -74.8%        -1.38      0.024  -56.607  < .001  ***
fixed_var[Variable]                  0.843  -15.7%        -0.17      0.016  -10.570  < .001  ***
annual_fee[20]                       0.287  -71.3%        -1.25      0.015  -83.818  < .001  ***
visamc[Visa ]                        0.970   -3.0%        -0.03      0.013   -2.404   0.016    *
date[November]                       0.467  -53.3%        -0.76      0.011  -71.571  < .001  ***
date[September]                      2.075  107.5%         0.73      0.010   70.940  < .001  ***
date[November]:fixed_var[Variable]   0.995   -0.5%        -0.00      0.029   -0.165   0.869
date[September]:fixed_var[Variable]  0.847  -15.3%        -0.17      0.021   -8.029  < .001  ***
bk_score                             0.989   -1.1%        -0.01      0.000  -88.459  < .001  ***

Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Pseudo R-squared (McFadden): 0.033
Pseudo R-squared (McFadden adjusted): 0.033
Area under the RO Curve (AUC): 0.662
Log-likelihood: -132932.839, AIC: 265881.678, BIC: 265979.552
Chi-squared: 9197.3, df(7), p.value < 0.001
Nr obs: 1,520,000

In [6]:
dct = rsm.levels_list(tools_mult_melt[['apr', 'fixed_var', 'annual_fee','visamc', 'date','bk_score']])
dct

{'apr': [16.8, 19.8, 14.9],
 'fixed_var': ['Fixed', 'Variable'],
 'annual_fee': [20, 0],
 'visamc': ['MC ', 'Visa '],
 'date': ['April', 'September', 'November'],
 'bk_score': [200, 250, 150]}

In [7]:
tools_mult_expand = rsm.expand_grid(dct)
tools_mult_expand

      apr fixed_var  annual_fee visamc       date  bk_score
0    16.8     Fixed          20    MC       April       200
1    16.8     Fixed          20    MC       April       250
2    16.8     Fixed          20    MC       April       150
3    16.8     Fixed          20    MC   September       200
4    16.8     Fixed          20    MC   September       250
..    ...       ...         ...    ...        ...       ...
211  14.9  Variable           0  Visa   September       250
212  14.9  Variable           0  Visa   September       150
213  14.9  Variable           0  Visa    November       200
214  14.9  Variable           0  Visa    November       250
215  14.9  Variable           0  Visa    November       150

[216 rows x 6 columns]

In [9]:
tools_mult_expand["pred_all_with_interaction"] = lr1.predict(tools_mult_expand)["prediction"]
tools_mult_expand

,apr,fixed_var,annual_fee,visamc,date,bk_score,pred_all_with_interaction
0,16.8,Fixed,20,MC,April,200,0.009994
1,16.8,Fixed,20,MC,April,250,0.005777
2,16.8,Fixed,20,MC,April,150,0.017233
3,16.8,Fixed,20,MC,September,200,0.020521
4,16.8,Fixed,20,MC,September,250,0.011917
...,...,...,...,...,...,...,...
211,14.9,Variable,0,Visa,September,250,0.058890
212,14.9,Variable,0,Visa,September,150,0.158840
213,14.9,Variable,0,Visa,November,200,0.027958
214,14.9,Variable,0,Visa,November,250,0.016288
215,14.9,Variable,0,Visa,November,150,0.047587

In here we average out the prediction score for each date and vismac to reduce the combination to only apr, fixed_var , annual_fee and bk_score.

In [10]:
prediction_with_interaction = tools_mult_expand.groupby(['apr', 'fixed_var', 'annual_fee','bk_score'])['pred_all_with_interaction'].mean().reset_index()
prediction_with_interaction

     apr fixed_var  annual_fee  bk_score  pred_all_with_interaction
0   14.9     Fixed           0       150                   0.127782
1   14.9     Fixed           0       200                   0.078965
2   14.9     Fixed           0       250                   0.047502
3   14.9     Fixed          20       150                   0.041546
4   14.9     Fixed          20       200                   0.024478
5   14.9     Fixed          20       250                   0.014285
6   14.9  Variable           0       150                   0.102517
7   14.9  Variable           0       200                   0.062293
8   14.9  Variable           0       250                   0.037058
9   14.9  Variable          20       150                   0.032343
10  14.9  Variable          20       200                   0.018939
11  14.9  Variable          20       250                   0.011012
12  16.8     Fixed           0       150                   0.064953
13  16.8     Fixed           0       200                   0.038771
14  16.8     Fixed           0       250                   0.022808
15  16.8     Fixed          20       150                   0.019864
16  16.8     Fixed          20       200                   0.011563
17  16.8     Fixed          20       250                   0.006699
18  16.8  Variable           0       150                   0.050988
19  16.8  Variable           0       200                   0.030152
20  16.8  Variable           0       250                   0.017636
21  16.8  Variable          20       150                   0.015343
22  16.8  Variable          20       200                   0.008904
23  16.8  Variable          20       250                   0.005150
24  19.8     Fixed           0       150                   0.036725
25  19.8     Fixed           0       200                   0.021580
26  19.8     Fixed           0       250                   0.012573
27  19.8     Fixed          20       150                   0.010931
28  19.8     Fixed          20       200                   0.006331
29  19.8     Fixed          20       250                   0.003658
30  19.8  Variable           0       150                   0.028540
31  19.8  Variable           0       200                   0.016679
32  19.8  Variable           0       250                   0.009686
33  19.8  Variable          20       150                   0.008416
34  19.8  Variable          20       200                   0.004866
35  19.8  Variable          20       250                   0.002808

## Model without interaction

This model is a comparison model which we built the simplest model with the least explanatory variable, which to do a comparison with the model with interaction term. We want to see if the interaction term is significant or not.

In [11]:
lr2 = rsm.model.logistic(
    data = {'tools_mult': tools_mult_melt},
    rvar = "resp",lev = 'resp', evar = ['apr', 'fixed_var', 'annual_fee','bk_score'],
    weights = 'freq'
)
lr2.summary()

Logistic regression (GLM)
Data                 : tools_mult
Response variable    : resp
Level                : resp
Explanatory variables: apr, fixed_var, annual_fee, bk_score
Weights used         : freq
Null hyp.: There is no effect of x on resp
Alt. hyp.: There is an effect of x on resp

                        OR     OR%  coefficient  std.error  z.value p.value
Intercept            0.036  -96.4%        -3.31      0.035  -95.624  < .001  ***
apr[16.8]            0.480  -52.0%        -0.73      0.016  -46.404  < .001  ***
apr[19.8]            0.263  -73.7%        -1.34      0.020  -66.447  < .001  ***
fixed_var[Variable]  0.744  -25.6%        -0.30      0.021  -14.230  < .001  ***
annual_fee[20]       0.290  -71.0%        -1.24      0.015  -84.711  < .001  ***
bk_score             1.003    0.3%         0.00      0.000   19.817  < .001  ***

Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Pseudo R-squared (McFadden): 0.033
Pseudo R-squared (McFadden adjusted): 0.033
Area under the RO Curve (AUC): 0.662
Log-likelihood: -132940.001, AIC: 265892.002, BIC: 265965.407
Chi-squared: 9182.976, df(5), p.value < 0.001
Nr obs: 1,520,000

In [12]:
dct2 = rsm.levels_list(tools_mult_melt[['apr', 'fixed_var', 'annual_fee', 'bk_score']])
dct2

{'apr': [16.8, 19.8, 14.9],
 'fixed_var': ['Fixed', 'Variable'],
 'annual_fee': [20, 0],
 'bk_score': [200, 250, 150]}

In [13]:
tools_mult_expand2 = rsm.expand_grid(dct2)
tools_mult_expand2

     apr fixed_var  annual_fee  bk_score
0   16.8     Fixed          20       200
1   16.8     Fixed          20       250
2   16.8     Fixed          20       150
3   16.8     Fixed           0       200
4   16.8     Fixed           0       250
5   16.8     Fixed           0       150
6   16.8  Variable          20       200
7   16.8  Variable          20       250
8   16.8  Variable          20       150
9   16.8  Variable           0       200
10  16.8  Variable           0       250
11  16.8  Variable           0       150
12  19.8     Fixed          20       200
13  19.8     Fixed          20       250
14  19.8     Fixed          20       150
15  19.8     Fixed           0       200
16  19.8     Fixed           0       250
17  19.8     Fixed           0       150
18  19.8  Variable          20       200
19  19.8  Variable          20       250
20  19.8  Variable          20       150
21  19.8  Variable           0       200
22  19.8  Variable           0       250
23  19.8  Variable           0       150
24  14.9     Fixed          20       200
25  14.9     Fixed          20       250
26  14.9     Fixed          20       150
27  14.9     Fixed           0       200
28  14.9     Fixed           0       250
29  14.9     Fixed           0       150
30  14.9  Variable          20       200
31  14.9  Variable          20       250
32  14.9  Variable          20       150
33  14.9  Variable           0       200
34  14.9  Variable           0       250
35  14.9  Variable           0       150

In [14]:
tools_mult_expand2["pred_all_without_interaction"] = lr2.predict(tools_mult_expand2)["prediction"]
tools_mult_expand2

     apr fixed_var  annual_fee  bk_score  pred_all_without_interaction
0   16.8     Fixed          20       200                      0.009897
1   16.8     Fixed          20       250                      0.011705
2   16.8     Fixed          20       150                      0.008366
3   16.8     Fixed           0       200                      0.033292
4   16.8     Fixed           0       250                      0.039205
5   16.8     Fixed           0       150                      0.028244
6   16.8  Variable          20       200                      0.007379
7   16.8  Variable          20       250                      0.008732
8   16.8  Variable          20       150                      0.006235
9   16.8  Variable           0       200                      0.024973
10  16.8  Variable           0       250                      0.029453
11  16.8  Variable           0       150                      0.021159
12  19.8     Fixed          20       200                      0.005445
13  19.8     Fixed          20       250                      0.006445
14  19.8     Fixed          20       150                      0.004599
15  19.8     Fixed           0       200                      0.018512
16  19.8     Fixed           0       250                      0.021859
17  19.8     Fixed           0       150                      0.015669
18  19.8  Variable          20       200                      0.004055
19  19.8  Variable          20       250                      0.004801
20  19.8  Variable          20       150                      0.003425
21  19.8  Variable           0       200                      0.013833
22  19.8  Variable           0       250                      0.016349
23  19.8  Variable           0       150                      0.011700
24  14.9     Fixed          20       200                      0.020419
25  14.9     Fixed          20       250                      0.024103
26  14.9     Fixed          20       150                      0.017288
27  14.9     Fixed           0       200                      0.067001
28  14.9     Fixed           0       250                      0.078416
29  14.9     Fixed           0       150                      0.057144
30  14.9  Variable          20       200                      0.015266
31  14.9  Variable          20       250                      0.018037
32  14.9  Variable          20       150                      0.012915
33  14.9  Variable           0       200                      0.050700
34  14.9  Variable           0       250                      0.059515
35  14.9  Variable           0       150                      0.043131

# Merge results from 2 models

In [15]:
prediction_with_interaction = pd.merge(prediction_with_interaction, tools_mult_expand2, on = ['apr', 'fixed_var', 'annual_fee','bk_score'])
prediction_with_interaction

,apr,fixed_var,annual_fee,bk_score,pred_all_with_interaction,pred_all_without_interaction
0,14.9,Fixed,0,150,0.127782,0.057144
1,14.9,Fixed,0,200,0.078965,0.067001
2,14.9,Fixed,0,250,0.047502,0.078416
3,14.9,Fixed,20,150,0.041546,0.017288
4,14.9,Fixed,20,200,0.024478,0.020419
5,14.9,Fixed,20,250,0.014285,0.024103
6,14.9,Variable,0,150,0.102517,0.043131
7,14.9,Variable,0,200,0.062293,0.050700
8,14.9,Variable,0,250,0.037058,0.059515
9,14.9,Variable,20,150,0.032343,0.012915
10,14.9,Variable,20,200,0.018939,0.015266
11,14.9,Variable,20,250,0.011012,0.018037
12,16.8,Fixed,0,150,0.064953,0.028244
13,16.8,Fixed,0,200,0.038771,0.033292
14,16.8,Fixed,0,250,0.022808,0.039205
15,16.8,Fixed,20,150,0.019864,0.008366
16,16.8,Fixed,20,200,0.011563,0.009897
17,16.8,Fixed,20,250,0.006699,0.011705
18,16.8,Variable,0,150,0.050988,0.021159
19,16.8,Variable,0,200,0.030152,0.024973
20,16.8,Variable,0,250,0.017636,0.029453
21,16.8,Variable,20,150,0.015343,0.006235
22,16.8,Variable,20,200,0.008904,0.007379
23,16.8,Variable,20,250,0.005150,0.008732
24,19.8,Fixed,0,150,0.036725,0.015669
25,19.8,Fixed,0,200,0.021580,0.018512
26,19.8,Fixed,0,250,0.012573,0.021859
27,19.8,Fixed,20,150,0.010931,0.004599
28,19.8,Fixed,20,200,0.006331,0.005445
29,19.8,Fixed,20,250,0.003658,0.006445
30,19.8,Variable,0,150,0.028540,0.011700
31,19.8,Variable,0,200,0.016679,0.013833
32,19.8,Variable,0,250,0.009686,0.016349
33,19.8,Variable,20,150,0.008416,0.003425
34,19.8,Variable,20,200,0.004866,0.004055
35,19.8,Variable,20,250,0.002808,0.004801

In [16]:
new_table = pd.merge(data2,prediction_with_interaction , on=['apr', 'fixed_var', 'annual_fee'], how='inner')

In [17]:
new_table

,offer,apr,fixed_var,annual_fee,clv150,clv200,clv250,bk_score,pred_all_with_interaction,pred_all_without_interaction
0,1,14.9,Fixed,20,83,63,33,150,0.041546,0.017288
1,1,14.9,Fixed,20,83,63,33,200,0.024478,0.020419
2,1,14.9,Fixed,20,83,63,33,250,0.014285,0.024103
3,2,14.9,Variable,20,93,73,43,150,0.032343,0.012915
4,2,14.9,Variable,20,93,73,43,200,0.018939,0.015266
5,2,14.9,Variable,20,93,73,43,250,0.011012,0.018037
6,3,14.9,Fixed,0,52,32,2,150,0.127782,0.057144
7,3,14.9,Fixed,0,52,32,2,200,0.078965,0.067001
8,3,14.9,Fixed,0,52,32,2,250,0.047502,0.078416
9,4,14.9,Variable,0,62,42,12,150,0.102517,0.043131
10,4,14.9,Variable,0,62,42,12,200,0.062293,0.050700
11,4,14.9,Variable,0,62,42,12,250,0.037058,0.059515
12,5,16.8,Fixed,20,103,83,53,150,0.019864,0.008366
13,5,16.8,Fixed,20,103,83,53,200,0.011563,0.009897
14,5,16.8,Fixed,20,103,83,53,250,0.006699,0.011705
15,6,16.8,Variable,20,113,93,63,150,0.015343,0.006235
16,6,16.8,Variable,20,113,93,63,200,0.008904,0.007379
17,6,16.8,Variable,20,113,93,63,250,0.005150,0.008732
18,7,16.8,Fixed,0,72,52,22,150,0.064953,0.028244
19,7,16.8,Fixed,0,72,52,22,200,0.038771,0.033292
20,7,16.8,Fixed,0,72,52,22,250,0.022808,0.039205
21,8,16.8,Variable,0,82,62,32,150,0.050988,0.021159
22,8,16.8,Variable,0,82,62,32,200,0.030152,0.024973
23,8,16.8,Variable,0,82,62,32,250,0.017636,0.029453
24,9,19.8,Fixed,20,131,111,81,150,0.010931,0.004599
25,9,19.8,Fixed,20,131,111,81,200,0.006331,0.005445
26,9,19.8,Fixed,20,131,111,81,250,0.003658,0.006445
27,10,19.8,Variable,20,141,121,91,150,0.008416,0.003425
28,10,19.8,Variable,20,141,121,91,200,0.004866,0.004055
29,10,19.8,Variable,20,141,121,91,250,0.002808,0.004801
30,11,19.8,Fixed,0,100,80,50,150,0.036725,0.015669
31,11,19.8,Fixed,0,100,80,50,200,0.021580,0.018512
32,11,19.8,Fixed,0,100,80,50,250,0.012573,0.021859
33,12,19.8,Variable,0,110,90,60,150,0.028540,0.011700
34,12,19.8,Variable,0,110,90,60,200,0.016679,0.013833
35,12,19.8,Variable,0,110,90,60,250,0.009686,0.016349

In here, we expect the low apr and low annual fee to get higher response probability.Thus by the result of the 2 models, we think that the prediction with interaction term would be more reasonable in our case.

## Expected CLV

Calculate the expected CLV for each customer. We use the model with interaction term to predict the response probability and then calculate the expected CLV for each customer.

In [18]:
def calculate_clv_profit(row):
    # Mapping bk_score to clv column name
    clv_column = f"clv{int(row['bk_score'])}"
    # Returning the calculated clv_profit
    return row[clv_column] * row['pred_all_with_interaction'] if clv_column in row else 0

new_table['clv_profit'] = new_table.apply(calculate_clv_profit, axis=1)

In [19]:
new_table = new_table.sort_values(by='pred_all_with_interaction', ascending=False)

In [20]:
new_table

,offer,apr,fixed_var,annual_fee,clv150,clv200,clv250,bk_score,pred_all_with_interaction,pred_all_without_interaction,clv_profit
6,3,14.9,Fixed,0,52,32,2,150,0.127782,0.057144,6.644646
9,4,14.9,Variable,0,62,42,12,150,0.102517,0.043131,6.356056
7,3,14.9,Fixed,0,52,32,2,200,0.078965,0.067001,2.526869
18,7,16.8,Fixed,0,72,52,22,150,0.064953,0.028244,4.676637
10,4,14.9,Variable,0,62,42,12,200,0.062293,0.050700,2.616323
21,8,16.8,Variable,0,82,62,32,150,0.050988,0.021159,4.181009
8,3,14.9,Fixed,0,52,32,2,250,0.047502,0.078416,0.095003
0,1,14.9,Fixed,20,83,63,33,150,0.041546,0.017288,3.448342
19,7,16.8,Fixed,0,72,52,22,200,0.038771,0.033292,2.016076
11,4,14.9,Variable,0,62,42,12,250,0.037058,0.059515,0.444694
30,11,19.8,Fixed,0,100,80,50,150,0.036725,0.015669,3.672498
3,2,14.9,Variable,20,93,73,43,150,0.032343,0.012915,3.007873
22,8,16.8,Variable,0,82,62,32,200,0.030152,0.024973,1.869419
33,12,19.8,Variable,0,110,90,60,150,0.028540,0.011700,3.139397
1,1,14.9,Fixed,20,83,63,33,200,0.024478,0.020419,1.542128
20,7,16.8,Fixed,0,72,52,22,250,0.022808,0.039205,0.501767
31,11,19.8,Fixed,0,100,80,50,200,0.021580,0.018512,1.726362
12,5,16.8,Fixed,20,103,83,53,150,0.019864,0.008366,2.045994
4,2,14.9,Variable,20,93,73,43,200,0.018939,0.015266,1.382530
23,8,16.8,Variable,0,82,62,32,250,0.017636,0.029453,0.564336
34,12,19.8,Variable,0,110,90,60,200,0.016679,0.013833,1.501066
15,6,16.8,Variable,20,113,93,63,150,0.015343,0.006235,1.733766
2,1,14.9,Fixed,20,83,63,33,250,0.014285,0.024103,0.471417
32,11,19.8,Fixed,0,100,80,50,250,0.012573,0.021859,0.628665
13,5,16.8,Fixed,20,103,83,53,200,0.011563,0.009897,0.959702
5,2,14.9,Variable,20,93,73,43,250,0.011012,0.018037,0.473503
24,9,19.8,Fixed,20,131,111,81,150,0.010931,0.004599,1.431988
35,12,19.8,Variable,0,110,90,60,250,0.009686,0.016349,0.581157
16,6,16.8,Variable,20,113,93,63,200,0.008904,0.007379,0.828082
27,10,19.8,Variable,20,141,121,91,150,0.008416,0.003425,1.186641
14,5,16.8,Fixed,20,103,83,53,250,0.006699,0.011705,0.355065
25,9,19.8,Fixed,20,131,111,81,200,0.006331,0.005445,0.702768
17,6,16.8,Variable,20,113,93,63,250,0.005150,0.008732,0.324439
28,10,19.8,Variable,20,141,121,91,200,0.004866,0.004055,0.588812
26,9,19.8,Fixed,20,131,111,81,250,0.003658,0.006445,0.296262
29,10,19.8,Variable,20,141,121,91,250,0.002808,0.004801,0.255570

# Test Data(create new model with test data)

After we run our test, we get the new data and build a new model with the test data since we want to use the current data to improve our model.

In [22]:
data3 = pd.read_csv('data/test_result.csv')

In [23]:
data3.dtypes

Unnamed: 0      int64
apr           float64
fixed_var      object
annual_fee      int64
nr_mailed       int64
non_resp        int64
resp            int64
bk_score        int64
dtype: object

In [38]:
tools_mult_melt_test = pd.melt(
    data3,
    id_vars=["apr", "fixed_var", "annual_fee",'bk_score'],
    value_vars=["resp", "non_resp"],
    var_name="resp",
    value_name="freq",
)
tools_mult_melt_test['apr'] = tools_mult_melt['apr'].astype('category')
tools_mult_melt_test['annual_fee'] = tools_mult_melt['annual_fee'].astype('category')
tools_mult_melt_test['bk_socre'] = tools_mult_melt['bk_score'].astype('category')
tools_mult_melt_test

     apr fixed_var annual_fee  bk_score      resp  freq bk_socre
0   16.8     Fixed         20       200      resp    95      200
1   16.8     Fixed          0       250      resp    93      200
2   19.8  Variable         20       150      resp   144      200
3   19.8  Variable          0       200      resp   160      200
4   14.9     Fixed         20       150      resp    10      250
5   14.9  Variable         20       150      resp    11      250
6   16.8     Fixed         20       200      resp    84      250
7   19.8  Variable         20       250      resp    83      250
8   16.8  Variable          0       200      resp    14      250
9   19.8  Variable          0       250      resp    14      250
10  14.9     Fixed         20       150      resp    56      150
11  14.9     Fixed          0       250      resp    64      150
12  14.9     Fixed         20       200  non_resp  3905      150
13  16.8     Fixed         20       250  non_resp  3907      150
14  16.8  Variable         20       150  non_resp  3856      200
15  16.8  Variable          0       200  non_resp  3840      200
16  19.8     Fixed         20       150  non_resp  3990      200
17  19.8  Variable          0       150  non_resp  3989      200
18  14.9     Fixed         20       200  non_resp  3916      250
19  14.9  Variable         20       250  non_resp  3917      250
20  16.8  Variable         20       200  non_resp  3986      250
21  19.8  Variable         20       250  non_resp  3986      250
22  16.8     Fixed          0       150  non_resp  3944      250
23  19.8     Fixed          0       250  non_resp  3936      250

In [39]:
lr_test = rsm.model.logistic(
    data = {'tools_mult': tools_mult_melt_test},
    rvar = "resp",lev = 'resp', evar = ['apr', 'fixed_var', 'annual_fee','bk_score'],
    weights = 'freq'
)
lr_test.summary()

Logistic regression (GLM)
Data                 : tools_mult
Response variable    : resp
Level                : resp
Explanatory variables: apr, fixed_var, annual_fee, bk_score
Weights used         : freq
Null hyp.: There is no effect of x on resp
Alt. hyp.: There is an effect of x on resp

                        OR     OR%  coefficient  std.error  z.value p.value
Intercept            0.010  -99.0%        -4.62      0.210  -22.005  < .001  ***
apr[16.8]            1.162   16.2%         0.15      0.112    1.341    0.18
apr[19.8]            1.925   92.5%         0.66      0.108    6.045  < .001  ***
fixed_var[Variable]  1.038    3.8%         0.04      0.071    0.528   0.597
annual_fee[20]       0.812  -18.8%        -0.21      0.078   -2.666   0.008   **
bk_score             1.002    0.2%         0.00      0.001    2.118   0.034    *

Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Pseudo R-squared (McFadden): 0.011
Pseudo R-squared (McFadden adjusted): 0.009
Area under the RO Curve (AUC): 0.605
Log-likelihood: -4137.924, AIC: 8287.848, BIC: 8340.522
Chi-squared: 89.052, df(5), p.value < 0.001
Nr obs: 48,000

In [40]:
dct3 = rsm.levels_list(tools_mult_melt_test[['apr', 'fixed_var', 'annual_fee', 'bk_score']])
dct3

{'apr': [16.8, 19.8, 14.9],
 'fixed_var': ['Fixed', 'Variable'],
 'annual_fee': [20, 0],
 'bk_score': [200, 250, 150]}

In [41]:
tools_mult_expand3 = rsm.expand_grid(dct3)
tools_mult_expand3

     apr fixed_var  annual_fee  bk_score
0   16.8     Fixed          20       200
1   16.8     Fixed          20       250
2   16.8     Fixed          20       150
3   16.8     Fixed           0       200
4   16.8     Fixed           0       250
5   16.8     Fixed           0       150
6   16.8  Variable          20       200
7   16.8  Variable          20       250
8   16.8  Variable          20       150
9   16.8  Variable           0       200
10  16.8  Variable           0       250
11  16.8  Variable           0       150
12  19.8     Fixed          20       200
13  19.8     Fixed          20       250
14  19.8     Fixed          20       150
15  19.8     Fixed           0       200
16  19.8     Fixed           0       250
17  19.8     Fixed           0       150
18  19.8  Variable          20       200
19  19.8  Variable          20       250
20  19.8  Variable          20       150
21  19.8  Variable           0       200
22  19.8  Variable           0       250
23  19.8  Variable           0       150
24  14.9     Fixed          20       200
25  14.9     Fixed          20       250
26  14.9     Fixed          20       150
27  14.9     Fixed           0       200
28  14.9     Fixed           0       250
29  14.9     Fixed           0       150
30  14.9  Variable          20       200
31  14.9  Variable          20       250
32  14.9  Variable          20       150
33  14.9  Variable           0       200
34  14.9  Variable           0       250
35  14.9  Variable           0       150

In [42]:
tools_mult_expand3["pred_all_test"] = lr_test.predict(tools_mult_expand3)["prediction"]
tools_mult_expand3

     apr fixed_var  annual_fee  bk_score  pred_all_test
0   16.8     Fixed          20       200       0.013167
1   16.8     Fixed          20       250       0.014378
2   16.8     Fixed          20       150       0.012056
3   16.8     Fixed           0       200       0.016172
4   16.8     Fixed           0       250       0.017655
5   16.8     Fixed           0       150       0.014811
6   16.8  Variable          20       200       0.013666
7   16.8  Variable          20       250       0.014923
8   16.8  Variable          20       150       0.012514
9   16.8  Variable           0       200       0.016783
10  16.8  Variable           0       250       0.018322
11  16.8  Variable           0       150       0.015372
12  19.8     Fixed          20       200       0.021634
13  19.8     Fixed          20       250       0.023607
14  19.8     Fixed          20       150       0.019823
15  19.8     Fixed           0       200       0.026521
16  19.8     Fixed           0       250       0.028925
17  19.8     Fixed           0       150       0.024311
18  19.8  Variable          20       200       0.022448
19  19.8  Variable          20       250       0.024492
20  19.8  Variable          20       150       0.020570
21  19.8  Variable           0       200       0.027512
22  19.8  Variable           0       250       0.030004
23  19.8  Variable           0       150       0.025222
24  14.9     Fixed          20       200       0.011354
25  14.9     Fixed          20       250       0.012401
26  14.9     Fixed          20       150       0.010395
27  14.9     Fixed           0       200       0.013952
28  14.9     Fixed           0       250       0.015235
29  14.9     Fixed           0       150       0.012775
30  14.9  Variable          20       200       0.011786
31  14.9  Variable          20       250       0.012872
32  14.9  Variable          20       150       0.010790
33  14.9  Variable           0       200       0.014480
34  14.9  Variable           0       250       0.015811
35  14.9  Variable           0       150       0.013260

In [43]:
final_table = pd.merge(new_table, tools_mult_expand3, on = ['apr', 'fixed_var', 'annual_fee','bk_score'])

In [44]:
final_table

,offer,apr,fixed_var,annual_fee,clv150,clv200,clv250,bk_score,pred_all_with_interaction,pred_all_without_interaction,clv_profit,pred_all_test
0,3,14.9,Fixed,0,52,32,2,150,0.127782,0.057144,6.644646,0.012775
1,4,14.9,Variable,0,62,42,12,150,0.102517,0.043131,6.356056,0.013260
2,3,14.9,Fixed,0,52,32,2,200,0.078965,0.067001,2.526869,0.013952
3,7,16.8,Fixed,0,72,52,22,150,0.064953,0.028244,4.676637,0.014811
4,4,14.9,Variable,0,62,42,12,200,0.062293,0.050700,2.616323,0.014480
5,8,16.8,Variable,0,82,62,32,150,0.050988,0.021159,4.181009,0.015372
6,3,14.9,Fixed,0,52,32,2,250,0.047502,0.078416,0.095003,0.015235
7,1,14.9,Fixed,20,83,63,33,150,0.041546,0.017288,3.448342,0.010395
8,7,16.8,Fixed,0,72,52,22,200,0.038771,0.033292,2.016076,0.016172
9,4,14.9,Variable,0,62,42,12,250,0.037058,0.059515,0.444694,0.015811
10,11,19.8,Fixed,0,100,80,50,150,0.036725,0.015669,3.672498,0.024311
11,2,14.9,Variable,20,93,73,43,150,0.032343,0.012915,3.007873,0.010790
12,8,16.8,Variable,0,82,62,32,200,0.030152,0.024973,1.869419,0.016783
13,12,19.8,Variable,0,110,90,60,150,0.028540,0.011700,3.139397,0.025222
14,1,14.9,Fixed,20,83,63,33,200,0.024478,0.020419,1.542128,0.011354
15,7,16.8,Fixed,0,72,52,22,250,0.022808,0.039205,0.501767,0.017655
16,11,19.8,Fixed,0,100,80,50,200,0.021580,0.018512,1.726362,0.026521
17,5,16.8,Fixed,20,103,83,53,150,0.019864,0.008366,2.045994,0.012056
18,2,14.9,Variable,20,93,73,43,200,0.018939,0.015266,1.382530,0.011786
19,8,16.8,Variable,0,82,62,32,250,0.017636,0.029453,0.564336,0.018322
20,12,19.8,Variable,0,110,90,60,200,0.016679,0.013833,1.501066,0.027512
21,6,16.8,Variable,20,113,93,63,150,0.015343,0.006235,1.733766,0.012514
22,1,14.9,Fixed,20,83,63,33,250,0.014285,0.024103,0.471417,0.012401
23,11,19.8,Fixed,0,100,80,50,250,0.012573,0.021859,0.628665,0.028925
24,5,16.8,Fixed,20,103,83,53,200,0.011563,0.009897,0.959702,0.013167
25,2,14.9,Variable,20,93,73,43,250,0.011012,0.018037,0.473503,0.012872
26,9,19.8,Fixed,20,131,111,81,150,0.010931,0.004599,1.431988,0.019823
27,12,19.8,Variable,0,110,90,60,250,0.009686,0.016349,0.581157,0.030004
28,6,16.8,Variable,20,113,93,63,200,0.008904,0.007379,0.828082,0.013666
29,10,19.8,Variable,20,141,121,91,150,0.008416,0.003425,1.186641,0.020570
30,5,16.8,Fixed,20,103,83,53,250,0.006699,0.011705,0.355065,0.014378
31,9,19.8,Fixed,20,131,111,81,200,0.006331,0.005445,0.702768,0.021634
32,6,16.8,Variable,20,113,93,63,250,0.005150,0.008732,0.324439,0.014923
33,10,19.8,Variable,20,141,121,91,200,0.004866,0.004055,0.588812,0.022448
34,9,19.8,Fixed,20,131,111,81,250,0.003658,0.006445,0.296262,0.023607
35,10,19.8,Variable,20,141,121,91,250,0.002808,0.004801,0.255570,0.024492

# Compare the prediction 
1.Interaction model built with historical data  
2.Model built with test data  
3.Average prediction score of model 1 and 2.

In [45]:
final_table['averge_pred_score'] = (final_table['pred_all_with_interaction'] + final_table['pred_all_test']) / 2

In [46]:
def calculate_clv_profit(row):
    # Mapping bk_score to clv column name
    clv_column = f"clv{int(row['bk_score'])}"
    # Returning the calculated clv_profit
    return row[clv_column] * row['pred_all_test'] if clv_column in row else 0

# Applying the function to each row of the DataFrame
final_table['clv_profit_test_prediction'] = final_table.apply(calculate_clv_profit, axis=1)

In [47]:
def calculate_clv_profit(row):
    # Mapping bk_score to clv column name
    clv_column = f"clv{int(row['bk_score'])}"
    # Returning the calculated clv_profit
    return row[clv_column] * row['averge_pred_score'] if clv_column in row else 0

# Applying the function to each row of the DataFrame
final_table['clv_profit_average_prediction'] = final_table.apply(calculate_clv_profit, axis=1)

In [48]:
final_table

,offer,apr,fixed_var,annual_fee,clv150,clv200,clv250,bk_score,pred_all_with_interaction,pred_all_without_interaction,clv_profit,pred_all_test,averge_pred_score,clv_profit_test_prediction,clv_profit_average_prediction
0,3,14.9,Fixed,0,52,32,2,150,0.127782,0.057144,6.644646,0.012775,0.070279,0.664324,3.654485
1,4,14.9,Variable,0,62,42,12,150,0.102517,0.043131,6.356056,0.013260,0.057889,0.822129,3.589093
2,3,14.9,Fixed,0,52,32,2,200,0.078965,0.067001,2.526869,0.013952,0.046458,0.446455,1.486662
3,7,16.8,Fixed,0,72,52,22,150,0.064953,0.028244,4.676637,0.014811,0.039882,1.066425,2.871531
4,4,14.9,Variable,0,62,42,12,200,0.062293,0.050700,2.616323,0.014480,0.038387,0.608175,1.612249
5,8,16.8,Variable,0,82,62,32,150,0.050988,0.021159,4.181009,0.015372,0.033180,1.260519,2.720764
6,3,14.9,Fixed,0,52,32,2,250,0.047502,0.078416,0.095003,0.015235,0.031368,0.030469,0.062736
7,1,14.9,Fixed,20,83,63,33,150,0.041546,0.017288,3.448342,0.010395,0.025970,0.862754,2.155548
8,7,16.8,Fixed,0,72,52,22,200,0.038771,0.033292,2.016076,0.016172,0.027471,0.840948,1.428512
9,4,14.9,Variable,0,62,42,12,250,0.037058,0.059515,0.444694,0.015811,0.026434,0.189733,0.317213
10,11,19.8,Fixed,0,100,80,50,150,0.036725,0.015669,3.672498,0.024311,0.030518,2.431093,3.051795
11,2,14.9,Variable,20,93,73,43,150,0.032343,0.012915,3.007873,0.010790,0.021566,1.003467,2.005670
12,8,16.8,Variable,0,82,62,32,200,0.030152,0.024973,1.869419,0.016783,0.023468,1.040573,1.454996
13,12,19.8,Variable,0,110,90,60,150,0.028540,0.011700,3.139397,0.025222,0.026881,2.774427,2.956912
14,1,14.9,Fixed,20,83,63,33,200,0.024478,0.020419,1.542128,0.011354,0.017916,0.715314,1.128721
15,7,16.8,Fixed,0,72,52,22,250,0.022808,0.039205,0.501767,0.017655,0.020232,0.388420,0.445093
16,11,19.8,Fixed,0,100,80,50,200,0.021580,0.018512,1.726362,0.026521,0.024050,2.121657,1.924009
17,5,16.8,Fixed,20,103,83,53,150,0.019864,0.008366,2.045994,0.012056,0.015960,1.241749,1.643872
18,2,14.9,Variable,20,93,73,43,200,0.018939,0.015266,1.382530,0.011786,0.015362,0.860348,1.121439
19,8,16.8,Variable,0,82,62,32,250,0.017636,0.029453,0.564336,0.018322,0.017979,0.586299,0.575318
20,12,19.8,Variable,0,110,90,60,200,0.016679,0.013833,1.501066,0.027512,0.022095,2.476110,1.988588
21,6,16.8,Variable,20,113,93,63,150,0.015343,0.006235,1.733766,0.012514,0.013928,1.414031,1.573898
22,1,14.9,Fixed,20,83,63,33,250,0.014285,0.024103,0.471417,0.012401,0.013343,0.409240,0.440328
23,11,19.8,Fixed,0,100,80,50,250,0.012573,0.021859,0.628665,0.028925,0.020749,1.446270,1.037468
24,5,16.8,Fixed,20,103,83,53,200,0.011563,0.009897,0.959702,0.013167,0.012365,1.092835,1.026269
25,2,14.9,Variable,20,93,73,43,250,0.011012,0.018037,0.473503,0.012872,0.011942,0.553491,0.513497
26,9,19.8,Fixed,20,131,111,81,150,0.010931,0.004599,1.431988,0.019823,0.015377,2.596878,2.014433
27,12,19.8,Variable,0,110,90,60,250,0.009686,0.016349,0.581157,0.030004,0.019845,1.800250,1.190704
28,6,16.8,Variable,20,113,93,63,200,0.008904,0.007379,0.828082,0.013666,0.011285,1.270939,1.049511
29,10,19.8,Variable,20,141,121,91,150,0.008416,0.003425,1.186641,0.020570,0.014493,2.900370,2.043506
30,5,16.8,Fixed,20,103,83,53,250,0.006699,0.011705,0.355065,0.014378,0.010539,0.762057,0.558561
31,9,19.8,Fixed,20,131,111,81,200,0.006331,0.005445,0.702768,0.021634,0.013983,2.401422,1.552095
32,6,16.8,Variable,20,113,93,63,250,0.005150,0.008732,0.324439,0.014923,0.010036,0.940149,0.632294
33,10,19.8,Variable,20,141,121,91,200,0.004866,0.004055,0.588812,0.022448,0.013657,2.716156,1.652484
34,9,19.8,Fixed,20,131,111,81,250,0.003658,0.006445,0.296262,0.023607,0.013632,1.912153,1.104207
35,10,19.8,Variable,20,141,121,91,250,0.002808,0.004801,0.255570,0.024492,0.013650,2.228793,1.242181

In [49]:
final_table2 = final_table[['apr', 'fixed_var', 'annual_fee', 'clv_profit','bk_score', 'clv_profit_test_prediction', 'clv_profit_average_prediction']]

In [50]:
data3

,Unnamed: 0,apr,fixed_var,annual_fee,nr_mailed,non_resp,resp,bk_score
0,1,14.9,Fixed,20,4000,3905,95,200
1,2,14.9,Fixed,20,4000,3907,93,250
2,3,14.9,Variable,0,4000,3856,144,150
3,4,14.9,Variable,0,4000,3840,160,200
4,5,16.8,Fixed,20,4000,3990,10,150
5,6,16.8,Variable,20,4000,3989,11,150
6,7,16.8,Fixed,0,4000,3916,84,200
7,8,16.8,Variable,0,4000,3917,83,250
8,9,19.8,Variable,20,4000,3986,14,200
9,10,19.8,Variable,20,4000,3986,14,250
10,11,19.8,Fixed,0,4000,3944,56,150
11,12,19.8,Fixed,0,4000,3936,64,250

#### Compare prediction and test result to choose the best one.

First calculate the test result response rate

In [51]:
data3['response_rate'] = data3['resp'] / (data3['resp'] + data3['non_resp'])
data3_sorted = data3.sort_values(by='response_rate', ascending=False)
data3_sorted.head(10)

,Unnamed: 0,apr,fixed_var,annual_fee,nr_mailed,non_resp,resp,bk_score,response_rate
3,4,14.9,Variable,0,4000,3840,160,200,0.04000
2,3,14.9,Variable,0,4000,3856,144,150,0.03600
0,1,14.9,Fixed,20,4000,3905,95,200,0.02375
1,2,14.9,Fixed,20,4000,3907,93,250,0.02325
6,7,16.8,Fixed,0,4000,3916,84,200,0.02100
7,8,16.8,Variable,0,4000,3917,83,250,0.02075
11,12,19.8,Fixed,0,4000,3936,64,250,0.01600
10,11,19.8,Fixed,0,4000,3944,56,150,0.01400
8,9,19.8,Variable,20,4000,3986,14,200,0.00350
9,10,19.8,Variable,20,4000,3986,14,250,0.00350

In [52]:
final_table2 = final_table[['apr', 'fixed_var', 'annual_fee','bk_score', 'pred_all_with_interaction', 'pred_all_test', 'averge_pred_score']]

In [53]:
final_table2_sorted_interation = final_table2.sort_values(by='pred_all_with_interaction', ascending=False)
final_table2_sorted_all = final_table2.sort_values(by='pred_all_test', ascending=False)
final_table2_sorted_avg = final_table2.sort_values(by='averge_pred_score', ascending=False)

1. compare all with interation and test:

In [54]:
final_table2_sorted_interation = final_table2_sorted_interation[['apr', 'fixed_var','annual_fee', 'bk_score', 'pred_all_with_interaction']]

In [55]:
final_table2_sorted_interation.head(10)

    apr fixed_var  annual_fee  bk_score  pred_all_with_interaction
0  14.9     Fixed           0       150                   0.127782
1  14.9  Variable           0       150                   0.102517
2  14.9     Fixed           0       200                   0.078965
3  16.8     Fixed           0       150                   0.064953
4  14.9  Variable           0       200                   0.062293
5  16.8  Variable           0       150                   0.050988
6  14.9     Fixed           0       250                   0.047502
7  14.9     Fixed          20       150                   0.041546
8  16.8     Fixed           0       200                   0.038771
9  14.9  Variable           0       250                   0.037058

2. Compare all and test:

In [56]:
final_table2_sorted_all = final_table2_sorted_all[['apr', 'fixed_var','annual_fee', 'bk_score', 'pred_all_test']]
final_table2_sorted_all.head(10)

     apr fixed_var  annual_fee  bk_score  pred_all_test
27  19.8  Variable           0       250       0.030004
23  19.8     Fixed           0       250       0.028925
20  19.8  Variable           0       200       0.027512
16  19.8     Fixed           0       200       0.026521
13  19.8  Variable           0       150       0.025222
35  19.8  Variable          20       250       0.024492
10  19.8     Fixed           0       150       0.024311
34  19.8     Fixed          20       250       0.023607
33  19.8  Variable          20       200       0.022448
31  19.8     Fixed          20       200       0.021634

In [57]:
data3_sorted.head(10)

,Unnamed: 0,apr,fixed_var,annual_fee,nr_mailed,non_resp,resp,bk_score,response_rate
3,4,14.9,Variable,0,4000,3840,160,200,0.04000
2,3,14.9,Variable,0,4000,3856,144,150,0.03600
0,1,14.9,Fixed,20,4000,3905,95,200,0.02375
1,2,14.9,Fixed,20,4000,3907,93,250,0.02325
6,7,16.8,Fixed,0,4000,3916,84,200,0.02100
7,8,16.8,Variable,0,4000,3917,83,250,0.02075
11,12,19.8,Fixed,0,4000,3936,64,250,0.01600
10,11,19.8,Fixed,0,4000,3944,56,150,0.01400
8,9,19.8,Variable,20,4000,3986,14,200,0.00350
9,10,19.8,Variable,20,4000,3986,14,250,0.00350

3. compare average and test:

In [58]:
final_table2_sorted_avg = final_table2_sorted_avg[['apr', 'fixed_var','annual_fee', 'bk_score', 'averge_pred_score']]
final_table2_sorted_avg.head(10)

     apr fixed_var  annual_fee  bk_score  averge_pred_score
0   14.9     Fixed           0       150           0.070279
1   14.9  Variable           0       150           0.057889
2   14.9     Fixed           0       200           0.046458
3   16.8     Fixed           0       150           0.039882
4   14.9  Variable           0       200           0.038387
5   16.8  Variable           0       150           0.033180
6   14.9     Fixed           0       250           0.031368
10  19.8     Fixed           0       150           0.030518
8   16.8     Fixed           0       200           0.027471
13  19.8  Variable           0       150           0.026881

In [59]:
data3_sorted.head(10)

,Unnamed: 0,apr,fixed_var,annual_fee,nr_mailed,non_resp,resp,bk_score,response_rate
3,4,14.9,Variable,0,4000,3840,160,200,0.04000
2,3,14.9,Variable,0,4000,3856,144,150,0.03600
0,1,14.9,Fixed,20,4000,3905,95,200,0.02375
1,2,14.9,Fixed,20,4000,3907,93,250,0.02325
6,7,16.8,Fixed,0,4000,3916,84,200,0.02100
7,8,16.8,Variable,0,4000,3917,83,250,0.02075
11,12,19.8,Fixed,0,4000,3936,64,250,0.01600
10,11,19.8,Fixed,0,4000,3944,56,150,0.01400
8,9,19.8,Variable,20,4000,3986,14,200,0.00350
9,10,19.8,Variable,20,4000,3986,14,250,0.00350

After we carefully compare the prediction and test result, we find that the model built with **average data (test + historical)** is the best one, which means we have similar prediction result with the actual data and the our predict model data.

In [60]:
## sort clv
final_table_sort_clv_profit_average_prediction = final_table.sort_values(by='clv_profit_average_prediction', ascending=False)
final_table_sort_clv_profit_average_prediction.head(12)

,offer,apr,fixed_var,annual_fee,clv150,clv200,clv250,bk_score,pred_all_with_interaction,pred_all_without_interaction,clv_profit,pred_all_test,averge_pred_score,clv_profit_test_prediction,clv_profit_average_prediction
0,3,14.9,Fixed,0,52,32,2,150,0.127782,0.057144,6.644646,0.012775,0.070279,0.664324,3.654485
1,4,14.9,Variable,0,62,42,12,150,0.102517,0.043131,6.356056,0.013260,0.057889,0.822129,3.589093
10,11,19.8,Fixed,0,100,80,50,150,0.036725,0.015669,3.672498,0.024311,0.030518,2.431093,3.051795
13,12,19.8,Variable,0,110,90,60,150,0.028540,0.011700,3.139397,0.025222,0.026881,2.774427,2.956912
3,7,16.8,Fixed,0,72,52,22,150,0.064953,0.028244,4.676637,0.014811,0.039882,1.066425,2.871531
5,8,16.8,Variable,0,82,62,32,150,0.050988,0.021159,4.181009,0.015372,0.033180,1.260519,2.720764
7,1,14.9,Fixed,20,83,63,33,150,0.041546,0.017288,3.448342,0.010395,0.025970,0.862754,2.155548
29,10,19.8,Variable,20,141,121,91,150,0.008416,0.003425,1.186641,0.020570,0.014493,2.900370,2.043506
26,9,19.8,Fixed,20,131,111,81,150,0.010931,0.004599,1.431988,0.019823,0.015377,2.596878,2.014433
11,2,14.9,Variable,20,93,73,43,150,0.032343,0.012915,3.007873,0.010790,0.021566,1.003467,2.005670
20,12,19.8,Variable,0,110,90,60,200,0.016679,0.013833,1.501066,0.027512,0.022095,2.476110,1.988588
16,11,19.8,Fixed,0,100,80,50,200,0.021580,0.018512,1.726362,0.026521,0.024050,2.121657,1.924009

In [61]:
final_table_sort_clv_profit_average_prediction = final_table_sort_clv_profit_average_prediction[['apr', 'fixed_var', 'annual_fee', 'bk_score', 'clv_profit_average_prediction']]    
final_table_sort_clv_profit_average_prediction.head(36)

     apr fixed_var  annual_fee  bk_score  clv_profit_average_prediction
0   14.9     Fixed           0       150                       3.654485
1   14.9  Variable           0       150                       3.589093
10  19.8     Fixed           0       150                       3.051795
13  19.8  Variable           0       150                       2.956912
3   16.8     Fixed           0       150                       2.871531
5   16.8  Variable           0       150                       2.720764
7   14.9     Fixed          20       150                       2.155548
29  19.8  Variable          20       150                       2.043506
26  19.8     Fixed          20       150                       2.014433
11  14.9  Variable          20       150                       2.005670
20  19.8  Variable           0       200                       1.988588
16  19.8     Fixed           0       200                       1.924009
33  19.8  Variable          20       200                       1.652484
17  16.8     Fixed          20       150                       1.643872
4   14.9  Variable           0       200                       1.612249
21  16.8  Variable          20       150                       1.573898
31  19.8     Fixed          20       200                       1.552095
2   14.9     Fixed           0       200                       1.486662
12  16.8  Variable           0       200                       1.454996
8   16.8     Fixed           0       200                       1.428512
35  19.8  Variable          20       250                       1.242181
27  19.8  Variable           0       250                       1.190704
14  14.9     Fixed          20       200                       1.128721
18  14.9  Variable          20       200                       1.121439
34  19.8     Fixed          20       250                       1.104207
28  16.8  Variable          20       200                       1.049511
23  19.8     Fixed           0       250                       1.037468
24  16.8     Fixed          20       200                       1.026269
32  16.8  Variable          20       250                       0.632294
19  16.8  Variable           0       250                       0.575318
30  16.8     Fixed          20       250                       0.558561
25  14.9  Variable          20       250                       0.513497
15  16.8     Fixed           0       250                       0.445093
22  14.9     Fixed          20       250                       0.440328
9   14.9  Variable           0       250                       0.317213
6   14.9     Fixed           0       250                       0.062736

In [62]:
rest_mail = 750000 - (4000 * 12)

**Generative AI (5 points): Describe in detail how your team used Generative AI-tools like ChatGPT to support your work on this case. Provide pdfs and/or screenshots of your "discussions" with these tools and comment on what things did and did not go well. Make sure to add discussion about your thought process and how you tried to maximize the benefits from using these tools. Also add any questions you may have about the assignment and the support you received from GenAI so we can discuss these topics in class.**

PLEASE SEE THE PDF FILE FOR THE ANSWERS TO THE QUESTIONS.